### ISSUE TITLE
Example sketch of Pro Micro 

### ISSUE THREAD

**Issue by karoria** [brianlow/Rotary#12]
The example sketch of Pro Micro informs that "These registers support interrupts on Pro Micro pins 8, 9, 10 or 11". But there is no pin 11 available on Pro Micro. I am stuck as I want to use 2 rotary encoders with 1 pro micro board. Please guide.
BTW, Thanks for this awesome library. It generates pretty robust cw and ccw.
Waiting for response.
Regards,
Ravi

**Comment by brianlow** [comment]
Looks like there are 5 pins that support external interrupt:

> The Pro Micro has five external interrupts, which allow you to instantly trigger a function when a pin goes either high or low (or both). If you attach an interrupt to an interrupt-enabled pin, you'll need to know the specific interrupt that pin triggers: pin 3 maps to interrupt 0 (INT0), pin 2 is interrupt 1 (INT1), pin 0 is interrupt 2 (INT2), pin 1 is interrupt 3 (INT3), and pin 7 is interrupt 4 (INT6).

https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/hardware-overview-pro-micro

Or alternatively you can poll using any pins that supports digital read. 

Closing since pretty old but feel free to re-open to continue the discussion
